export const OPENWEATHERMAP_DOMAIN =
  process.env.REACT_APP_OPENWEATHERMAP_DOMAIN;
export const OPENWEATHERMAP_API_DOMAIN =
  process.env.REACT_APP_OPENWEATHERMAP_API_DOMAIN;
export const OPENWEATHERMAP_API_KEY =
  process.env.REACT_APP_OPENWEATHERMAP_API_KEY;
